import = ["~/.alacritty/themes/kanagawa.toml"]

[window]
opacity = 0.95
blur = true

[font]
size = 12

[font.normal]
family = "UbuntuMono Nerd Font Mono"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[colors]
transparent_background_colors = true

# Set this to true if we want to be able to see the selected option in bios (adjust bright/white)
draw_bold_text_with_bright_colors = false
